[project]
name = "tata-genai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "pdf2image>=1.17.0",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.13",
    "pypdf>=6.19.0",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
    "sqlalchemy>=2.0.54",
    "streamlit>=1.64.0",
    "torchvision>=0.29.1",
    "tqdm>=4.70.1",
]
[server]
fileWatcherType = "none"
